name: Oru Kabir
favicon: null
layout_spectrum: 1
typography_spectrum: 0.32415
title: Oru Kabir
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a0a0a0'
    - '#c2c2c2'
    - '#454545'
    - '#eeeeee'
    - '#060606'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
