name: Oru Kabir
favicon: null
layout_spectrum: 1
typography_spectrum: 0.32415
title: Oru Kabir
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d1d746'
    - '#3f9ec9'
    - '#d92c75'
    - '#1c1b19'
  brandStrength: 1
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
