analytics: {}
color:
  brandColors:
    - '#a0a0a0'
    - '#c2c2c2'
    - '#454545'
    - '#eeeeee'
    - '#060606'
  brandStrength: 0.5
  lightness: 0.5
  rhythmicContrast: 0.5
  saturation: 0.504504
cta: {}
layout_spectrum: 1
name: Oru Kabir
opengraph: {}
purpose: []
typography_spectrum: 0.32415
